version: '3.8'

services:
  application:
    build: .
    container_name: php-apache-container
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./ssh:/root/.ssh
    environment:
      GIT_USER_NAME: "JordanTatue"
      GIT_USER_EMAIL: "tatuejordan@gmail.com"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # Web interface

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql-data:
